version: '3'
services:
  web:
    image: asia-northeast3-docker.pkg.dev/cloudtype/sel/bluehongc-claim-jbclaim:2rrqq2blmpxm07n
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always
